name: "Luis Chaves"
title: "lucha6 personal website"
navbar:
  title: "Luis Chaves"
  left:
    - text: "About"
      href: about.html
    - text: "Exploratory Data Analysis"
      href: EDA.html
    - text: "Systems Virology"
      href: omics.html
  right:
    - icon: fa-envelope fa-lg
      href: contact.html
    - icon: fa-github fa-lg
      href: http://github.com/lc5415
    - icon: fa-linkedin fa-lg
      href: https://www.linkedin.com/in/lucha6/
output:
  html_document:
    theme: jekyll-theme-leap-day
    css: 'styles.css'