theme:jekyll-theme-leap-day
name: "Luis Chaves"
output_dir: "."
navbar:
  title: "Luis Chaves"
  left:
    - text: "Exploratory Data Analysis"
      href: EDA/COVID_EDA.html
    - text: "Systems Virology"
      href: omics.html
  right:
    - icon: fa-envelope fa-lg
      href: contact.html
    - icon: fa-github fa-lg
      href: http://github.com/lc5415
    - icon: fa-linkedin fa-lg
      href: https://www.linkedin.com/in/lucha6/